name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - "*"
  schedule:
  - cron: '0 0 * * *'

jobs:
 php-tests:
   runs-on: ubuntu-latest
   timeout-minutes: 15
   env:
      COMPOSER_NO_INTERACTION: 1
   
   strategy:
      matrix:
        php: [8.1, 8.0]
        dependency-version: [prefer-lowest, prefer-stable]

   name: P${{ matrix.php }} - ${{ matrix.dependency-version }}
      
   steps:
     - name: Checkout Code
       uses: actions/checkout@v2
       
     - name: Setup PHP
       uses: shivammathur/setup-php@v2
       with:
         php-version: ${{ matrix.php }}
         coverage: none
         tools: composer:v2
         
     - name: Install dependencies
       run: |
         composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress

     - name: PHPUnit Tests
       uses: php-actions/phpunit@v3
       with:
         bootstrap: vendor/autoload.php
         configuration: phpunit.xml
